---
- name: Create a new user
  hosts: all
  become: true
  vars:
    new_user: testuser
    new_user_password: testpassword
  tasks:
  - name: Create new user
    user:
      name: "{{ new_user }}"
      password: "{{ new_user_password | password_hash('sha512') }}"
      state: present
  - name: Add user to sudo group
    user:
      name: "{{ new_user }}"
      groups: sudo
      append: true
